version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  api:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/jobdb
      - JWT_SECRET=local_dev_secret_change_me
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
    ports: ["4000:4000"]
  web:
    build: ./frontend
    depends_on:
      - api
    ports: ["5173:80"]
volumes:
  mongo_data:
